import {test,expect} from '@playwright/test'
const token='browser-test-admin-token-minimum-32-bytes'
async function unlock(page:import('@playwright/test').Page){
  await page.goto('/admin/')
  await page.getByLabel('Admin token').fill(token)
  await page.getByRole('button',{name:'解锁控制台'}).click()
  await expect(page.getByRole('heading',{name:'账号与连接',exact:true})).toBeVisible()
}
test('admin authentication, secret memory, API instructions and responsive layout',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/admin/')
  await page.getByLabel('Admin token').fill('incorrect')
  await page.getByRole('button',{name:'解锁控制台'}).click()
  await expect(page.getByRole('alert')).toContainText('管理令牌不正确')
  await page.getByLabel('Admin token').fill(token)
  await page.getByRole('button',{name:'解锁控制台'}).click()
  await expect(page.getByRole('heading',{name:'还没有连接账号'})).toBeVisible()
  expect(await page.evaluate(()=>[localStorage.length,sessionStorage.length])).toEqual([0,0])
  expect(await page.content()).not.toContain(token)
  await page.screenshot({path:'test-results/console-desktop.png',fullPage:true})
  await page.getByRole('button',{name:'API 接入',exact:true}).click()
  await expect(page.getByRole('heading',{name:'一个端点，接入你的应用'})).toBeVisible()
  await expect(page.locator('pre')).toContainText('x-api-key: <BRIDGE_API_KEY>')
  await page.getByRole('button',{name:'账号与连接',exact:true}).click()
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('button',{name:'开始 OAuth 登录'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/console-mobile.png',fullPage:true})
  await page.reload()
  await expect(page.getByRole('heading',{name:'连接你的 AI 工作流'})).toBeVisible()
  expect(errors).toEqual([])
})
test('real admin routes create PKCE authorization, reject mismatched state, and cancel',async({page})=>{
  await unlock(page)
  await page.getByRole('button',{name:'开始 OAuth 登录'}).click()
  const link=page.getByRole('link',{name:'打开官方授权页面'})
  await expect(link).toBeVisible()
  const url=new URL((await link.getAttribute('href'))!)
  expect(url.origin).toBe('https://claude.com');expect(url.searchParams.get('code_challenge_method')).toBe('S256')
  expect(await link.getAttribute('rel')).toContain('noreferrer')
  await page.getByLabel('授权码',{exact:true}).fill('invalid-code#wrong-state')
  await page.getByRole('button',{name:'提交授权码'}).click()
  await expect(page.getByRole('alert')).toContainText('state does not match')
  await page.screenshot({path:'test-results/console-oauth.png',fullPage:true})
  await page.getByRole('button',{name:'取消本次登录'}).click()
  await expect(page.getByRole('status')).toContainText('已取消登录')
  await page.getByRole('button',{name:'锁定控制台'}).click()
  await expect(page.getByLabel('Admin token')).toHaveValue('')
})
test('polls successful login, renders safe account metadata, confirms logout',async({page})=>{
  // The provider is not contacted: backend PKCE/token/redb integration is tested in Rust.
  let loggedIn=false
  const account=()=>({logged_in:loggedIn,email:loggedIn?'demo@example.com':null,method:'claudeai',provider:'anthropic',organization:'Example Team',subscription:'claude_pro',storage:'redb'})
  const service={version:'0.1.0',bind:'127.0.0.1:8791',max_concurrency:4,available_slots:4,api_key_required:true,request_timeout_seconds:180,credential_mode:'redb_oauth',messages_path:'/v1/messages'}
  const login={id:'demo',status:'waiting',authorization_url:'https://claude.com/cai/oauth/authorize?state=mock&code_challenge=mock',message:null,expires_at:new Date(Date.now()+600000).toISOString()}
  await page.route('**/api/admin/status',route=>route.fulfill({json:{account:account(),login:null,service}}))
  await page.route('**/api/admin/oauth/start',route=>route.fulfill({status:202,json:login}))
  await page.route('**/api/admin/oauth',route=>route.fulfill({json:{login:{...login,status:loggedIn?'succeeded':'waiting',authorization_url:loggedIn?null:login.authorization_url}}}))
  await page.route('**/api/admin/oauth/demo/code',async route=>{loggedIn=true;await route.fulfill({json:{accepted:true}})})
  await page.route('**/api/admin/logout',async route=>{loggedIn=false;await route.fulfill({json:{logged_out:true}})})
  await unlock(page)
  await page.getByRole('button',{name:'开始 OAuth 登录'}).click()
  await page.getByLabel('授权码',{exact:true}).fill('code#mock')
  await page.getByRole('button',{name:'提交授权码'}).click()
  await expect(page.getByRole('heading',{name:'连接另一个账号'})).toBeVisible()
  await expect(page.getByRole('status')).toContainText('账号登录成功')
  await expect(page.getByText('redb 本地数据库')).toBeVisible()
  await page.screenshot({path:'test-results/console-connected.png',fullPage:true})
  await page.getByRole('button',{name:'退出服务账号',exact:true}).click()
  await page.getByRole('button',{name:'确认退出服务账号'}).click()
  await expect(page.getByRole('heading',{name:'还没有连接账号'})).toBeVisible()
})
